theme: jekyll-theme-minimal

title: Kyoomin Kim
logo: /images/avatar2.png
locale: en_US

owner:
  name: Kyoomin Kim
  avatar: /images/avatar2.png
  bio: Undergraduate Math-CS Student at UC San Diego
  description: Undergraduate Math-CS Student at UC San Diego

repository: kevink856/kevink856.github.io
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "Blog comment"
