theme: jekyll-theme-minimal

title: Personal Website of Kevin Kim


owner:
  name: Kyoomin Kim
  avatar: avatar.png
  bio: "Undergraduate Math-CS Student as University of California - San Diego"
  email: kyk011@ucsd.edu
  linkedin: kevink856
  github: kevink856
