theme: jekyll-theme-minimal

title: Kyoomin Kim
logo: /images/avatar.png
locale: en_US

owner:
  name: Kyoomin Kim
  avatar: /images/avatar.png
  bio: Undergraduate Math-CS Student at University of California - San Diego
  description: Undergraduate Math-CS Student at University of California - San Diego
  email: kyk011@ucsd.edu
  linkedin: kevink856
  github: kevink856
